# Generated by Django 3.1.1 on 2020-10-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201024_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='caption',
            field=models.TextField(default='تویح مختصر و مفید', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='products/'),
        ),
    ]
