# Generated by Django 3.1.1 on 2020-10-26 18:27

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201025_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behdashti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('caption', models.TextField(default='تویح مختصر و مفید', max_length=100)),
                ('detail', models.TextField(default='توضیحات کامل', max_length=400)),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(null=True, upload_to=products.models.media_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tebi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('caption', models.TextField(default='تویح مختصر و مفید', max_length=100)),
                ('detail', models.TextField(default='توضیحات کامل', max_length=400)),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(null=True, upload_to=products.models.media_upload_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
